# **Numpy**



## **1. Array Creation**

In [20]:
import numpy as np

# Create arrays
a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones((2, 3))
d = np.full((2, 3), 7)
e = np.eye(3)
f = np.arange(0, 10, 2)
g = np.linspace(0, 1, 5)
h = np.random.rand(2, 3)
i = np.random.randint(0, 10, (2, 3))

print("Array a:", a)
print("Zeros array b:", b)
print("Ones array c:", c)
print("Full array d:", d)
print("Identity matrix e:", e)
print("Arange array f:", f)
print("Linspace array g:", g)
print("Random array h:", h)
print("Random integers array i:", i)

Array a: [1 2 3]
Zeros array b: [[0. 0. 0.]
 [0. 0. 0.]]
Ones array c: [[1. 1. 1.]
 [1. 1. 1.]]
Full array d: [[7 7 7]
 [7 7 7]]
Identity matrix e: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange array f: [0 2 4 6 8]
Linspace array g: [0.   0.25 0.5  0.75 1.  ]
Random array h: [[0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561]]
Random integers array i: [[2 7 2]
 [0 0 4]]


## **2. Array Inspection**

### Shape and Size

In [2]:
# Shape and size
print("Shape of array a:", a.shape)
print("Size of array b:", b.size)
print("Number of dimensions in array c:", c.ndim)

Shape of array a: (3,)
Size of array b: 6
Number of dimensions in array c: 2


### Data Type

In [3]:
# Data type
print("Data type of array a:", a.dtype)
print("Change data type of array a to float:", a.astype(float))

Data type of array a: int64
Change data type of array a to float: [1. 2. 3.]


### Indexing and Slicing

In [4]:
# Indexing and slicing
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Original array:\n", arr)
print("Element at position (0, 1):", arr[0, 1])
print("First row:", arr[0, :])
print("First column:", arr[:, 0])
print("Boolean indexing, elements > 3:\n", arr[arr > 3])

Original array:
 [[1 2 3]
 [4 5 6]]
Element at position (0, 1): 2
First row: [1 2 3]
First column: [1 4]
Boolean indexing, elements > 3:
 [4 5 6]


## **3. Array Manipulation**

### Reshaping

In [5]:
# Reshaping
arr = np.arange(8)
print("Original array:", arr)

reshaped_arr = arr.reshape((2, 4))
print("Reshaped array:\n", reshaped_arr)

Original array: [0 1 2 3 4 5 6 7]
Reshaped array:
 [[0 1 2 3]
 [4 5 6 7]]


### Transposing



In [6]:
# Transposing
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Original array:\n", arr)
print("Transposed array:\n", arr.transpose())
print("Swap axes (0, 1):\n", arr.swapaxes(0, 1))


Original array:
 [[1 2 3]
 [4 5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
Swap axes (0, 1):
 [[1 4]
 [2 5]
 [3 6]]


### Concatenation

In [7]:
# Concatenation
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Vertical stack:\n", np.vstack((arr1, arr2)))
print("Horizontal stack:\n", np.hstack((arr1, arr2)))
print("Concatenate along axis 0:\n", np.concatenate((arr1, arr2), axis=0))


Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]
Concatenate along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Splitting

In [8]:
# Splitting
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("Split into two:\n", np.split(arr, 2, axis=1))
print("Horizontal split:\n", np.hsplit(arr, 2))
print("Vertical split:\n", np.vsplit(arr, 2))

Split into two:
 [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
Horizontal split:
 [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
Vertical split:
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


## **4. Mathematical Operations**

### Element-wise Operations

In [9]:
# Element-wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", np.add(a, b))
print("Subtraction:", np.subtract(a, b))
print("Multiplication:", np.multiply(a, b))
print("Division:", np.divide(a, b))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


### Aggregate Functions

In [10]:
# Aggregate functions
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))

Sum: 21
Mean: 3.5
Median: 3.5
Standard deviation: 1.707825127659933
Variance: 2.9166666666666665
Min: 1
Max: 6


### Linear Algebra

In [11]:
# Linear algebra
arr = np.array([[1, 2], [3, 4]])

print("Dot product:\n", np.dot(arr, arr))
print("Matrix multiplication:\n", np.matmul(arr, arr))
print("Inverse:\n", np.linalg.inv(arr))
print("Eigenvalues and eigenvectors:\n", np.linalg.eig(arr))
print("Singular value decomposition:\n", np.linalg.svd(arr))

Dot product:
 [[ 7 10]
 [15 22]]
Matrix multiplication:
 [[ 7 10]
 [15 22]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues and eigenvectors:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
Singular value decomposition:
 SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))


## **5. Statistical Functions**

In [12]:
# Statistical functions
arr = np.random.randn(100)

print("Percentile (50th):", np.percentile(arr, 50))
print("Histogram:", np.histogram(arr))
print("Bincount:", np.bincount(np.random.randint(0, 10, 100)))

Percentile (50th): -0.05730755624916985
Histogram: (array([ 3,  2,  9, 17, 25, 21, 17,  1,  2,  3]), array([-2.71860077, -2.17239294, -1.62618512, -1.0799773 , -0.53376948,
        0.01243834,  0.55864616,  1.10485398,  1.6510618 ,  2.19726962,
        2.74347744]))
Bincount: [11 11  6  9  9 12  8  6 16 12]


## 6. **Broadcasting**

In [13]:
# Broadcasting
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print("Broadcasting example:\n", a + b)

Broadcasting example:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


## **7. Random Sampling**

In [14]:
# Random sampling
np.random.seed(0)

print("Random choice:", np.random.choice([1, 2, 3, 4, 5], size=3))
print("Random shuffle:")

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)

print(arr)

Random choice: [5 1 4]
Random shuffle:
[1 3 2 5 4]


## **8. Saving and Loading Data**

### Saving

In [15]:
# Saving
arr = np.array([1, 2, 3, 4, 5])

np.save('array.npy', arr)
np.savez('array.npz', arr1=arr, arr2=arr*2)
np.savetxt('array.txt', arr)

### Loading

In [17]:
# Loading
loaded_arr = np.load('array.npy')
print("Loaded array:", loaded_arr)

loaded_npz = np.load('array.npz')
print("Loaded .npz file arrays:", loaded_npz['arr1'], loaded_npz['arr2'])

loaded_txt = np.loadtxt('array.txt')
print("Loaded text file array:", loaded_txt)

Loaded array: [1 2 3 4 5]
Loaded .npz file arrays: [1 2 3 4 5] [ 2  4  6  8 10]
Loaded text file array: [1. 2. 3. 4. 5.]
